export default {
	login: 'ScytheDraven47',
	id: 22137371,
	node_id: 'MDQ6VXNlcjIyMTM3Mzcx',
	avatar_url: 'https://avatars.githubusercontent.com/u/22137371?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/ScytheDraven47',
	html_url: 'https://github.com/ScytheDraven47',
	followers_url: 'https://api.github.com/users/ScytheDraven47/followers',
	following_url:
		'https://api.github.com/users/ScytheDraven47/following{/other_user}',
	gists_url: 'https://api.github.com/users/ScytheDraven47/gists{/gist_id}',
	starred_url:
		'https://api.github.com/users/ScytheDraven47/starred{/owner}{/repo}',
	subscriptions_url:
		'https://api.github.com/users/ScytheDraven47/subscriptions',
	organizations_url: 'https://api.github.com/users/ScytheDraven47/orgs',
	repos_url: 'https://api.github.com/users/ScytheDraven47/repos',
	events_url: 'https://api.github.com/users/ScytheDraven47/events{/privacy}',
	received_events_url:
		'https://api.github.com/users/ScytheDraven47/received_events',
	type: 'User',
	site_admin: false,
	name: 'Ben Rogers-McKee',
	company: null,
	blog: '',
	location: 'Canterbury, NZ',
	email: null,
	hireable: null,
	bio: null,
	twitter_username: null,
	public_repos: 8,
	public_gists: 0,
	followers: 1,
	following: 0,
	created_at: '2016-09-11T22:18:16Z',
	updated_at: '2021-11-01T02:16:11Z',
}
